In [23]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("postgresql://analyst:password123@localhost:5432/bank_analytics")

csv_path = "../data/raw/Comprehensive_Banking_Database.csv"

df = pd.read_csv(csv_path)

display(df.groupby("Customer ID")["TransactionID"].nunique().sort_values(ascending=False).head(10)
)
#display(df.shape)
#display(df.columns)
#display(df.info())

clients_cols = [
    "Customer ID",
    "First Name",
    "Last Name",
    "Age",
    "Gender",
    "City",
    "Date Of Account Opening",
]

clients_df = df[clients_cols].drop_duplicates(subset=["Customer ID"])
#clients_df.head()

clients_df = clients_df.rename(columns={
    "Customer ID": "client_id",
    "First Name": "first_name",
    "Last Name": "last_name",
    "Age": "age",
    "Gender": "gender",
    "City": "city",
    "Date Of Account Opening": "account_opening_date",
})

display(clients_df.head())

accounts_cols = [
    "Customer ID",
    "Account Type",
    "Account Balance",
    "Branch ID",
    "Date Of Account Opening",
]

accounts_df = df[accounts_cols].drop_duplicates(subset=["Customer ID", "Account Type"])

accounts_df["account_id"] = (
    accounts_df["Customer ID"].astype(str) + "_" + accounts_df["Account Type"].astype(str)
)

accounts_df = accounts_df.rename(columns={
    "Customer ID": "client_id",
    "Account Type": "account_type",
    "Account Balance": "account_balance",
    "Branch ID": "branch_code",
    "Date Of Account Opening": "opening_date",
})

accounts_df = accounts_df[[
    "account_id",
    "client_id",
    "account_type",
    "branch_code",
    "account_balance",
    "opening_date",
]]


display(accounts_df.head())

transactions_cols = [
    "Customer ID",
    "Account Type",
    "TransactionID",
    "Transaction Date",
    "Transaction Type",
    "Transaction Amount",
    "Account Balance After Transaction",
]

transactions_df = df[transactions_cols].dropna(subset=["TransactionID"])

transactions_df["account_id"] = (
    transactions_df["Customer ID"].astype(str) + "_" + transactions_df["Account Type"].astype(str)
)

transactions_df = transactions_df.rename(columns={
    "TransactionID": "transaction_id",
    "Transaction Date": "transaction_date",
    "Transaction Type": "transaction_type",
    "Transaction Amount": "amount",
    "Account Balance After Transaction": "balance_after",
})


transactions_df = transactions_df[[
    "transaction_id",
    "account_id",
    "transaction_date",
    "transaction_type",
    "amount",
    "balance_after",
]]

display(transactions_df.head())

Customer ID
1       1
3331    1
3338    1
3337    1
3336    1
3335    1
3334    1
3333    1
3332    1
3330    1
Name: TransactionID, dtype: int64

,client_id,first_name,last_name,age,gender,city,account_opening_date
0,1,Joshua,Hall,45,Male,Fort Worth,5/26/2006
1,2,Mark,Taylor,47,Female,Louisville,3/2/2006
2,3,Joseph,Flores,25,Female,Philadelphia,7/19/2015
3,4,Kevin,Lee,52,Other,Oklahoma City,1/30/2008
4,5,Linda,Johnson,68,Other,Phoenix,5/25/2021

,account_id,client_id,account_type,branch_code,account_balance,opening_date
0,1_Current,1,Current,43,1313.38,5/26/2006
1,2_Current,2,Current,63,5988.46,3/2/2006
2,3_Current,3,Current,82,8277.88,7/19/2015
3,4_Savings,4,Savings,41,7487.21,1/30/2008
4,5_Savings,5,Savings,9,6993.55,5/25/2021

,transaction_id,account_id,transaction_date,transaction_type,amount,balance_after
0,1,1_Current,12/7/2023,Withdrawal,1457.61,2770.99
1,2,2_Current,4/27/2023,Deposit,1660.99,7649.45
2,3,3_Current,4/5/2023,Deposit,839.91,7437.97
3,4,4_Savings,7/28/2023,Withdrawal,4908.89,12396.10
4,5,5_Savings,1/16/2023,Transfer,589.07,6404.48