In [11]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sqlalchemy import create_engine

engine = create_engine("postgresql://analyst:password123@localhost:5432/bank_analytics")

df = pd.read_sql('SELECT * FROM transactions', engine)

print("--affichage  du  début du tableau")
display(df.head())

print("--affichage  des lignes et les colonnes")
display(df.shape)


print("--affichage ue types de donnée par colonne")
display(df.dtypes)

print("--affichage du nombre de  valeurs manquantes dans le dataframe")
display(df.isna().sum())

print("--affiche des statistiques descriptives pour les colonnes numériques")
display(df.describe())

--affichage  du  début du tableau

,transaction_id,account_id,transaction_date,transaction_type,amount,balance_after
0,1,1_Current,2023-12-07,Withdrawal,1457.61,2770.99
1,2,2_Current,2023-04-27,Deposit,1660.99,7649.45
2,3,3_Current,2023-04-05,Deposit,839.91,7437.97
3,4,4_Savings,2023-07-28,Withdrawal,4908.89,12396.10
4,5,5_Savings,2023-01-16,Transfer,589.07,6404.48

--affichage  des lignes et les colonnes

(5000, 6)

--affichage ue types de donnée par colonne

transaction_id               int64
account_id                  object
transaction_date    datetime64[ns]
transaction_type            object
amount                     float64
balance_after              float64
dtype: object

--affichage du nombre de  valeurs manquantes dans le dataframe

transaction_id      0
account_id          0
transaction_date    0
transaction_type    0
amount              0
balance_after       0
dtype: int64

--affiche des statistiques descriptives pour les colonnes numériques

,transaction_id,transaction_date,amount,balance_after
count,5000.000000,5000,5000.000000,5000.000000
mean,2500.500000,2023-06-30 09:21:01.440000256,2508.501144,5037.418898
min,1.000000,2023-01-01 00:00:00,10.570000,-4878.760000
25%,1250.750000,2023-04-01 00:00:00,1241.150000,2047.205000
50%,2500.500000,2023-06-30 00:00:00,2494.025000,5089.785000
75%,3750.250000,2023-09-27 00:00:00,3796.222500,8036.367500
max,5000.000000,2023-12-31 00:00:00,4998.390000,14911.380000
std,1443.520003,NaN,1450.194986,4053.220017